import './slider.js'
import './parallax.js'
import './customScrollBar.js'
import './modal.js'
import './dynamicAdapt.js'
import './filter.js'
//import './filter-2.js'
import '../blocks/nav/nav.js'
import '../blocks/sort/sort.js'
import '../blocks/grid-masonry/grid-masonry.js'
import '../blocks/masonry-card/masonry-card.js'
import '../blocks/search/search.js'
import '../blocks/lang/lang.js'
import '../blocks/account/account.js'
import '../blocks/footer/footer.js'
import '../blocks/burger/burger.js'
import './tabs.js'



